# backend/Dockerfile
FROM node:20-alpine

RUN apk add --no-cache openssl bash

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate --schema=./src/prisma/schema.prisma

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
